### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by phlind** [whateverforever/zettelwarmer#1]
When I run it, I get the following error:

```
Traceback (most recent call last):
  File "/Users/philipp/.scripts/zettelwarmer.py", line 204, in <module>
    main(**params)
  File "/Users/philipp/.scripts/zettelwarmer.py", line 144, in main
    plot_age_heatmap(ages)
  File "/Users/philipp/.scripts/zettelwarmer.py", line 26, in plot_age_heatmap
    padded_ages_mins = np.pad(
  File "<__array_function__ internals>", line 5, in pad
  File "/usr/local/lib/python3.8/site-packages/numpy/lib/arraypad.py", line 803, in pad
    _set_pad_area(roi, axis, width_pair, value_pair)
  File "/usr/local/lib/python3.8/site-packages/numpy/lib/arraypad.py", line 147, in _set_pad_area
    padded[left_slice] = value_pair[0]
ValueError: cannot convert float NaN to integer
```

**Comment by whateverforever** [comment]
Hm.. bizarre. How many files do you have in the folder? For now, I just removed usage of `np.pad()` and replaced it with much simpler list logic. Does the most recent commit work for you?

**Comment by phlind** [comment]
Ok, now it seems to work. But I had an error again for the second time I chose "visualize only". The third time it worked again.

```
Traceback (most recent call last):
  File "/Users/philipp/.scripts/zettelwarmer.py", line 202, in <module>
    main(**params)
  File "/Users/philipp/.scripts/zettelwarmer.py", line 138, in main
    sample_zettels = np.random.choice(
  File "mtrand.pyx", line 933, in numpy.random.mtrand.RandomState.choice
ValueError: probabilities do not sum to 1
```

Is it normal that the scale looks like this at the beginning?

![Bildschirmfoto 2021-02-25 um 19 50 44](https://user-images.githubusercontent.com/30386310/109201983-c21cb280-77a2-11eb-8eaf-b1e4467059db.png)

**Comment by whateverforever** [comment]
Managed to reproduce it, should be fixed now. As for the colorbar scale, yeah that is like that in the first day, I'll see if I can fix it later
